application: crosswordgamestats
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static
  
- url: /static
  static_dir: static
  
- url: /app*
  script: handlers.app
  login: required
  
- url: /.*
  script: handlers.app
  
libraries:
- name: jinja2
  version: latest