application: scrabble
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static
  
- url: /static
  static_dir: static
  
- url: /.*
  script: handlers.app